name: gh-pages

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - master

jobs:

  publish:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: doc/environment.yaml
        environment-name: doc-build

    - name: Run doxygen
      run: |
        echo ${{ github.ref }}
        echo ${{ github.event_name }}
