name: gh-pages

on:
  push:
    branches:
      - test

jobs:

  publish:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:

    - name: Run doxygen
      run: |
        echo ${{ github.ref }}
        echo ${{ github.event_name }}
