name: gh-pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  publish:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set conda environment "test"
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: doc/environment.yaml
        activate-environment: test
        auto-activate-base: false

    - name: Run doxygen
      run: |
        cmake -B build -S . -DHIGHFIVE_USE_BOOST:Bool=OFF
        cmake --build build --target doc

    - name: Deploy to GitHub Pages
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: build/doc/html
        jekyll: false
        keep_history: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
