name: HighFive_Integration_tests

on:
  push:
    branches:
      - ci_test
      - release/**
  pull_request:
    branches:
      - master
      - release/**
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'doc/**'

env:
  BUILD_TYPE: RelWithDebInfo
  INSTALL_DIR: ${{github.workspace}}/install

jobs:

  MorphIO:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Install libraries"
      run: sudo apt-get update && sudo apt-get install libboost-all-dev libhdf5-dev libeigen3-dev

    - name: Build
      run: |
        CMAKE_OPTIONS=(-DHIGHFIVE_EXAMPLES:BOOL=False -DHIGHFIVE_UNIT_TESTS:BOOL=False)
        source $GITHUB_WORKSPACE/.github/build.sh

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        make install
        git clone https://github.com/BlueBrain/MorphIO.git --recursive
        cd MorphIO
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DEXTERNAL_HIGHFIVE=True
        cmake --build . --config $BUILD_TYPE --parallel 2 --verbose
        ctest
